schema.json = https://json-schema.org/draft/2020-12/schema
applicator.json = https://json-schema.org/draft/2020-12/meta/applicator
unevaluated.json = https://json-schema.org/draft/2020-12/meta/unevaluated
meta-data.json = https://json-schema.org/draft/2020-12/meta/meta-data
content.json = https://json-schema.org/draft/2020-12/meta/content
core.json = https://json-schema.org/draft/2020-12/meta/core
format-annotation.json = https://json-schema.org/draft/2020-12/meta/format-annotation
validation.json = https://json-schema.org/draft/2020-12/meta/validation
